### ISSUE TITLE
http requests don't seem to work over https://cyber-yozh.com/

### ISSUE THREAD

**Issue by strong-banana** [artemtam/cyber-yozh#11]
Current target: http://cfmc.ru/

Mixed Content: The page at '<URL>' was loaded over HTTPS, but requested an insecure resource '<URL>'. This request has been blocked; the content must be served over HTTPS.

(only works when executed in local (HTTP) environment) 

cheers ✌️

**Comment by e27182** [comment]
![image](https://user-images.githubusercontent.com/14309815/156188646-8cb975f0-c0be-4f68-b04e-83a53a55a613.png)

**Comment by e27182** [comment]
So, it works in FF in Kali for example, but in all WebKit-based browsers (like Chrome, Opera, IE)in Windows (at least) - not.

**Comment by alxdrlitreev** [comment]
Sorry, was my typo. Fixed.

**Comment by artemtam** [comment]
This commit introduced it: https://github.com/alxdrlitreev/slavaukraine/commit/23116330cd35bd4fc59abbc55298bb3d273ca00f

We were aware that HTTP won't work due to browsers behavior – mixed-contend is blocked, but unfortunately made a typo. Really sorry :(

Right now it is fixed. Thanks for reporting!
