### ISSUE TITLE
Thread number is reset to default without page refresh

### ISSUE THREAD

**Issue by ymikhailenko** [artemtam/cyber-yozh#4]
Steps to reproduce:

1. Set threads to 100
2. Start attack
3. Wait ~10-30 min

-> Threads are reset to 10

**Comment by ymikhailenko** [comment]
Seems like when new targets are fetched window is being reloaded and all entered data is lost.

https://github.com/artemtam/cyber-yozh/blob/3698e46583648729bc908ff20578d5d1a58deca0/components/AttackForm.tsx#L28

**Comment by artemtam** [comment]
Page reloads automatically when the version is changed in the control center response. 

The threads number is saved in localStorage; however, due to the bug, it is not taken into account after reloading. This line is 99% causes the bug, it should be before `startAttack` call + number of threads should be passed to `startAttack` as an argument (because state update happens on the next tick):

https://github.com/artemtam/cyber-yozh/blob/3698e46583648729bc908ff20578d5d1a58deca0/components/AttackForm.tsx#L43

**Comment by artemtam** [comment]
Would you mind making a PR?

**Comment by ymikhailenko** [comment]
Only if there is no other option, 'cause this would take a while: I'm not familiar with the code.
Need to install, debug, fix, test, etc. Takes time

**Comment by artemtam** [comment]
Then I will fix it tomorrow
